###################################################
##                                               ##
##           WildInspect Configuration           ##
##              Developed by Ome_R               ##
##                                               ##
###################################################

# What is the command of the plugin?
commands:
- 'f inspect'
- 'faction inspect'

# A list of roles that can use the command.
# FactionsUUID: RECRUIT, NORMAL, MODERATOR, ADMIN
# MassiveFactions: RECRUIT, MEMBER, OFFICER, LEADER
# Towny: configured.
required-roles:
- MODERATOR
- ADMIN