###################################################
##                                               ##
##           WildInspect Configuration           ##
##              Developed by Ome_R               ##
##                                               ##
###################################################

# What commands should be used as inspect toggle command?
commands:
- 'f inspect'
- 'faction inspect'

# A list of roles that can use the command.
# FactionsUUID: RECRUIT, NORMAL, MODERATOR, COLEADER, ADMIN
# SaberFactions: RECRUIT, NORMAL, MODERATOR, COLEADER, LEADER
# MassiveFactions: RECRUIT, MEMBER, OFFICER, LEADER
# Towny: configured.
required-roles:
- MODERATOR
- COLEADER
- ADMIN
- LEADER

# History limits of the inspect mode.
# If you want to disable the feature, set the limit to -1.
history-limit:
  # Date limit. Limit the maximum date that can be viewed using the inspect mode.
  date: -1
  # Page limit. Limit the maximum amount of pages that can be viewed.
  page: -1

# Cooldown interval between checks.
cooldown: 5000

# Should ops be hidden in the inspect mode?
hide-ops: true

# Set a permission to use the inspect mode of WildInspect.
# If you wish to disable the feature, set it to ''.
inspect-permission: ''
