###################################################
##                                               ##
##           WildInspect Configuration           ##
##              Developed by Ome_R               ##
##                                               ##
###################################################

# What commands should be used as inspect toggle command?
commands:
- 'f inspect'
- 'faction inspect'

# A list of roles that can use the command.
# FactionsUUID: RECRUIT, NORMAL, MODERATOR, ADMIN
# MassiveFactions: RECRUIT, MEMBER, OFFICER, LEADER
# Towny: configured.
required-roles:
- MODERATOR
- ADMIN

# History limits of the inspect mode.
# If you want to disable the feature, set the limit to -1.
history-limit:
  # Date limit. Limit the maximum date that can be viewed using the inspect mode.
  date: -1
  # Page limit. Limit the maximum amount of pages that can be viewed.
  page: -1