name: WildInspect
version: ${project.version}
main: com.bgsoftware.wildinspect.WildInspectPlugin

description: Inspect block changes, chest transactions and more!
website: https://bg-software.com/
api-version: 1.13
author: Ome_R

depend:
  - CoreProtect

softdepend:
  - AcidIsland
  - ASkyBlock
  - BentoBox
  - Factions
  - GriefPrevention
  - SuperiorSkyblock
  - Towny
  - Villages

commands:
  wildinspect:
    description: Reload configuration files
    aliases: [wi]

permissions:
  wildinspect.reload:
    description: Access to reload configuration files