name: WildInspect
version: 2.2.2
main: com.bgsoftware.wildinspect.WildInspectPlugin
description: Inspect block changes, chest transactions and more!
website: http://bg-software.com/
author: Ome_R
depends: CoreProtect
softdepend: [AcidIsland, ASkyBlock, BentoBox, Factions, GriefPrevention, SuperiorSkyblock, Towny, Villages]
commands:
  wildinspect:
    description: Reload configuration files
    aliases: [wi]